
const UPDATE_POINT_OF_SALE = 1;
const INSERT_STORE = 2;
const UPDATE_STORE = 3;
const DELETE_STORE = 4;
const VIEW_STORE = 5;
const UPDATE_STOCK_STATUS = 6;
const VIEW_HISTORY_SALE = 7;
const DELETE_HISTORY_SALE = 8;
const VIEW_HISTORY_SYSTEM = 9;
const DELETE_HISTORY_SYSTEM = 10;

module.exports = {
    UPDATE_POINT_OF_SALE,
    INSERT_STORE,
    UPDATE_STORE,
    DELETE_HISTORY_SALE,
    DELETE_HISTORY_SYSTEM,
    DELETE_STORE,
    VIEW_HISTORY_SALE,
    UPDATE_STOCK_STATUS,
    VIEW_STORE, 
    VIEW_HISTORY_SYSTEM
}